<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-13 at 14:53:31.
 */
class ReadPostsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ReadPosts
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ReadPosts;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ReadPosts::readAllPosts
     * @todo   Implement testReadAllPosts().
     */
    public function testReadAllPosts() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReadPosts::test
     * @todo   Implement testTest().
     */
    public function testTest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReadPosts::Analyze
     * @todo   Implement testAnalyze().
     */
    public function testAnalyze() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
