<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-13 at 14:53:32.
 */
class SearchCompanyTest extends PHPUnit_Framework_TestCase {

    /**
     * @var SearchCompany
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SearchCompany;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers SearchCompany::analyzeCompany
     * @todo   Implement testAnalyzeCompany().
     */
    public function testAnalyzeCompany() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
