<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-13 at 14:53:32.
 */
class SearchNameTest extends PHPUnit_Framework_TestCase {

    /**
     * @var SearchName
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SearchName;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers SearchName::analyzeName
     * @todo   Implement testAnalyzeName().
     */
    public function testAnalyzeName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchName::clearName
     * @todo   Implement testClearName().
     */
    public function testClearName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchName::compareName
     * @todo   Implement testCompareName().
     */
    public function testCompareName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
